install:
	mvn install assembly:single
	
run:
	java -jar target/sonar-modelbus-client-0.0.1-SNAPSHOT-jar-with-dependencies.jar
	
wincpy:
	copy target\sonar-modelbus-client-0.0.1-SNAPSHOT-jar-with-dependencies.jar "%MODELBUS_ROOT%\bin"
	
lincpy:
	