
package org.sonar.plugins.modelbus.metrinoclient.metrino;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.annotation.Generated;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-12-16T21:29:30.898+01:00
 * Generated source version: 2.6.1
 * 
 */
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-12-16T21:29:30.898+01:00", comments = "Apache CXF 2.6.1")
public final class MetrinoService_MetrinoServicePort_Client {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-12-16T21:29:30.898+01:00")
    private static final QName SERVICE_NAME = new QName("http://www.modelbus.org/MetrinoService/", "MetrinoServiceService");

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-12-16T21:29:30.898+01:00")
    private MetrinoService_MetrinoServicePort_Client() {
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-12-16T21:29:30.898+01:00")
    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MetrinoServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MetrinoServiceService ss = new MetrinoServiceService(wsdlURL, SERVICE_NAME);
        MetrinoService port = ss.getMetrinoServicePort();  
        
        {
        System.out.println("Invoking satisfiesAllConstraints...");
        java.lang.String _satisfiesAllConstraints_model = "";
        java.lang.String _satisfiesAllConstraints_metricModel = "";
        boolean _satisfiesAllConstraints__return = port.satisfiesAllConstraints(_satisfiesAllConstraints_model, _satisfiesAllConstraints_metricModel);
        System.out.println("satisfiesAllConstraints.result=" + _satisfiesAllConstraints__return);


        }
        {
        System.out.println("Invoking getDiagram...");
        java.lang.String _getDiagram_model = "";
        java.lang.String _getDiagram_metricModel = "";
        java.lang.String _getDiagram_measurand = "";
        long _getDiagram_timeChecked = 0;
        byte[] _getDiagram__return = port.getDiagram(_getDiagram_model, _getDiagram_metricModel, _getDiagram_measurand, _getDiagram_timeChecked);
        System.out.println("getDiagram.result=" + _getDiagram__return);


        }
        {
        System.out.println("Invoking checkModel...");
        java.lang.String _checkModel_model = "";
        java.lang.String _checkModel_metricModel = "";
        port.checkModel(_checkModel_model, _checkModel_metricModel);


        }

        System.exit(0);
    }

}
