
package org.sonar.plugins.modelbus.wsclient.messages;

import javax.annotation.Generated;
import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-11-17T21:23:47.817+01:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "NonExistingResourceException", targetNamespace = "http://www.modelbus.org/Repository/")
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.817+01:00", comments = "Apache CXF 2.6.1")
public class NonExistingResourceException extends Exception {
    
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.817+01:00")
    private org.sonar.plugins.modelbus.wsclient.messages.RepositoryException nonExistingResourceException;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.817+01:00")
    public NonExistingResourceException() {
        super();
    }
    
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.817+01:00")
    public NonExistingResourceException(String message) {
        super(message);
    }
    
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.817+01:00")
    public NonExistingResourceException(String message, Throwable cause) {
        super(message, cause);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.817+01:00")
    public NonExistingResourceException(String message, org.sonar.plugins.modelbus.wsclient.messages.RepositoryException nonExistingResourceException) {
        super(message);
        this.nonExistingResourceException = nonExistingResourceException;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.817+01:00")
    public NonExistingResourceException(String message, org.sonar.plugins.modelbus.wsclient.messages.RepositoryException nonExistingResourceException, Throwable cause) {
        super(message, cause);
        this.nonExistingResourceException = nonExistingResourceException;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.817+01:00")
    public org.sonar.plugins.modelbus.wsclient.messages.RepositoryException getFaultInfo() {
        return this.nonExistingResourceException;
    }
}
