
package org.sonar.plugins.modelbus.wsclient.messages;

import javax.annotation.Generated;
import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-11-17T21:23:47.838+01:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "RepositoryAuthentifcationException", targetNamespace = "http://www.modelbus.org/Repository/")
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.838+01:00", comments = "Apache CXF 2.6.1")
public class RepositoryAuthentificationException extends Exception {
    
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.838+01:00")
    private org.sonar.plugins.modelbus.wsclient.messages.RepositoryException repositoryAuthentifcationException;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.838+01:00")
    public RepositoryAuthentificationException() {
        super();
    }
    
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.838+01:00")
    public RepositoryAuthentificationException(String message) {
        super(message);
    }
    
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.838+01:00")
    public RepositoryAuthentificationException(String message, Throwable cause) {
        super(message, cause);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.838+01:00")
    public RepositoryAuthentificationException(String message, org.sonar.plugins.modelbus.wsclient.messages.RepositoryException repositoryAuthentifcationException) {
        super(message);
        this.repositoryAuthentifcationException = repositoryAuthentifcationException;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.838+01:00")
    public RepositoryAuthentificationException(String message, org.sonar.plugins.modelbus.wsclient.messages.RepositoryException repositoryAuthentifcationException, Throwable cause) {
        super(message, cause);
        this.repositoryAuthentifcationException = repositoryAuthentifcationException;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.838+01:00")
    public org.sonar.plugins.modelbus.wsclient.messages.RepositoryException getFaultInfo() {
        return this.repositoryAuthentifcationException;
    }
}
