package org.sonar.plugins.modelbus.wsclient.messages;

import java.net.MalformedURLException; 
import java.net.URL;
import javax.annotation.Generated;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-11-17T17:52:27.025+01:00
 * Generated source version: 2.6.1
 * 
 */
@WebServiceClient(name = "RepositoryServiceService", 
                  wsdlLocation = "file:/home/arsenij/workspace/sonar-modelbus-plugin/src/main/resources/wsdl/modelbusrepository.wsdl",
                  targetNamespace = "http://www.modelbus.org/Repository/") 
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T17:52:27.025+01:00", comments = "Apache CXF 2.6.1")
public class RepositoryServiceService extends Service {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T17:52:27.025+01:00")
    public final static URL WSDL_LOCATION;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T17:52:27.025+01:00")
    public final static QName SERVICE = new QName("http://www.modelbus.org/Repository/", "RepositoryServiceService");
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T17:52:27.025+01:00")
    public final static QName RepositoryPort = new QName("http://www.modelbus.org/Repository/", "RepositoryPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/arsenij/workspace/sonar-modelbus-plugin/src/main/resources/wsdl/modelbusrepository.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RepositoryServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/arsenij/workspace/sonar-modelbus-plugin/src/main/resources/wsdl/modelbusrepository.wsdl");
        }
        WSDL_LOCATION = url;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T17:52:27.025+01:00")
    public RepositoryServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T17:52:27.025+01:00")
    public RepositoryServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T17:52:27.025+01:00")
    public RepositoryServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T17:52:27.025+01:00")
    public RepositoryServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T17:52:27.025+01:00")
    public RepositoryServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T17:52:27.025+01:00")
    public RepositoryServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns Repository
     */
    @WebEndpoint(name = "RepositoryPort")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T17:52:27.025+01:00")
    public Repository getRepositoryPort() {
        return super.getPort(RepositoryPort, Repository.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Repository
     */
    @WebEndpoint(name = "RepositoryPort")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T17:52:27.025+01:00")
    public Repository getRepositoryPort(WebServiceFeature... features) {
        return super.getPort(RepositoryPort, Repository.class, features);
    }

}
