
package org.sonar.plugins.modelbus.wsclient.repository;

import javax.annotation.Generated;
import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-11-17T21:23:47.930+01:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "ConstraintViolationException", targetNamespace = "http://www.modelbus.org/Repository/")
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.930+01:00", comments = "Apache CXF 2.6.1")
public class ConstraintViolationException extends Exception {
    
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.930+01:00")
    private org.sonar.plugins.modelbus.wsclient.repository.RepositoryException constraintViolationException;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.930+01:00")
    public ConstraintViolationException() {
        super();
    }
    
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.930+01:00")
    public ConstraintViolationException(String message) {
        super(message);
    }
    
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.930+01:00")
    public ConstraintViolationException(String message, Throwable cause) {
        super(message, cause);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.930+01:00")
    public ConstraintViolationException(String message, org.sonar.plugins.modelbus.wsclient.repository.RepositoryException constraintViolationException) {
        super(message);
        this.constraintViolationException = constraintViolationException;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.930+01:00")
    public ConstraintViolationException(String message, org.sonar.plugins.modelbus.wsclient.repository.RepositoryException constraintViolationException, Throwable cause) {
        super(message, cause);
        this.constraintViolationException = constraintViolationException;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.930+01:00")
    public org.sonar.plugins.modelbus.wsclient.repository.RepositoryException getFaultInfo() {
        return this.constraintViolationException;
    }
}
