package org.sonar.plugins.modelbus.wsclient.repository;

import javax.annotation.Generated;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-11-17T21:23:47.960+01:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://www.modelbus.org/Repository/", name = "Repository")
@XmlSeeAlso({ObjectFactory.class, net.java.dev.jaxb.array.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.960+01:00", comments = "Apache CXF 2.6.1")
public interface Repository {

    @WebMethod(action = "http://www.modelbus.org/Repository/checkOutModelWithRevision")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.960+01:00")
    public void checkOutModelWithRevision(
        @WebParam(partName = "session", mode = WebParam.Mode.INOUT, name = "session", targetNamespace = "http://www.modelbus.org/Repository/")
        javax.xml.ws.Holder<Session> session,
        @WebParam(partName = "modelUri", name = "modelUri", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.String modelUri,
        @WebParam(partName = "model", mode = WebParam.Mode.OUT, name = "model", targetNamespace = "http://www.modelbus.org/Repository/")
        javax.xml.ws.Holder<byte[]> model,
        @WebParam(partName = "revision", name = "revision", targetNamespace = "http://www.modelbus.org/Repository/")
        long revision
    ) throws UnresolvedReferencesException, RepositoryRuntimeException, NonExistingResourceException, RepositoryAuthentificationException;

    @WebResult(name = "successful", targetNamespace = "http://www.modelbus.org/Repository/", partName = "successful")
    @WebMethod(action = "http://www.modelbus.org/Repository/control")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.960+01:00")
    public boolean control(
        @WebParam(partName = "session", name = "session", targetNamespace = "http://www.modelbus.org/Repository/")
        Session session,
        @WebParam(partName = "fragmentUri", name = "fragmentUri", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.String fragmentUri,
        @WebParam(partName = "fragmentFileLocation", name = "fragmentFileLocation", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.String fragmentFileLocation,
        @WebParam(partName = "logMessage", name = "logMessage", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.String logMessage
    ) throws NonExistingResourceException, RepositoryRuntimeException, LockedException, RepositoryAuthentificationException;

    @WebMethod(action = "http://www.modelbus.org/Repository/checkInModel")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.960+01:00")
    public void checkInModel(
        @WebParam(partName = "session", mode = WebParam.Mode.INOUT, name = "session", targetNamespace = "http://www.modelbus.org/Repository/")
        javax.xml.ws.Holder<Session> session,
        @WebParam(partName = "modelUri", name = "modelUri", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.String modelUri,
        @WebParam(partName = "model", name = "model", targetNamespace = "http://www.modelbus.org/Repository/")
        byte[] model,
        @WebParam(partName = "enableDependencies", name = "enableDependencies", targetNamespace = "http://www.modelbus.org/Repository/")
        boolean enableDependencies,
        @WebParam(partName = "logMessage", name = "logMessage", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.String logMessage,
        @WebParam(partName = "checksum", mode = WebParam.Mode.OUT, name = "checksum", targetNamespace = "http://www.modelbus.org/Repository/")
        javax.xml.ws.Holder<java.lang.String> checksum
    ) throws UnresolvedReferencesException, InvalidValueException, ConstraintViolationException, RepositoryRuntimeException, LockedException, RepositoryAuthentificationException;

    @WebMethod(action = "http://www.modelbus.org/Repository/checkInFile")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.960+01:00")
    public void checkInFile(
        @WebParam(partName = "session", mode = WebParam.Mode.INOUT, name = "session", targetNamespace = "http://www.modelbus.org/Repository/")
        javax.xml.ws.Holder<Session> session,
        @WebParam(partName = "fileUri", name = "fileUri", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.String fileUri,
        @WebParam(partName = "fileContent", name = "fileContent", targetNamespace = "http://www.modelbus.org/Repository/")
        byte[] fileContent,
        @WebParam(partName = "logMessage", name = "logMessage", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.String logMessage,
        @WebParam(partName = "checksum", mode = WebParam.Mode.OUT, name = "checksum", targetNamespace = "http://www.modelbus.org/Repository/")
        javax.xml.ws.Holder<java.lang.String> checksum
    ) throws InvalidValueException, RepositoryRuntimeException, LockedException, RepositoryAuthentificationException;

    @WebResult(name = "successful", targetNamespace = "http://www.modelbus.org/Repository/", partName = "successful")
    @WebMethod(action = "http://www.modelbus.org/Repository/unpublishService")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.960+01:00")
    public boolean unpublishService(
        @WebParam(partName = "session", name = "session", targetNamespace = "http://www.modelbus.org/Repository/")
        Session session,
        @WebParam(partName = "properties", name = "properties", targetNamespace = "http://www.modelbus.org/Repository/")
        ServiceProperties properties
    ) throws RepositoryRuntimeException, InvalidServiceDescriptionException, RepositoryAuthentificationException;

    @WebMethod(action = "http://www.modelbus.org/Repository/commitChangeModel")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.960+01:00")
    public void commitChangeModel(
        @WebParam(partName = "session", mode = WebParam.Mode.INOUT, name = "session", targetNamespace = "http://www.modelbus.org/Repository/")
        javax.xml.ws.Holder<Session> session,
        @WebParam(partName = "messageID", name = "messageID", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.String messageID,
        @WebParam(partName = "modelUri", name = "modelUri", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.String modelUri,
        @WebParam(partName = "changeModelContent", name = "changeModelContent", targetNamespace = "http://www.modelbus.org/Repository/")
        byte[] changeModelContent,
        @WebParam(partName = "successful", mode = WebParam.Mode.OUT, name = "successful", targetNamespace = "http://www.modelbus.org/Repository/")
        javax.xml.ws.Holder<java.lang.Boolean> successful
    ) throws InvalidValueException, RepositoryRuntimeException, RepositoryAuthentificationException;

    @WebResult(name = "successful", targetNamespace = "http://www.modelbus.org/Repository/", partName = "successful")
    @WebMethod(action = "http://www.modelbus.org/Repository/lock")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.960+01:00")
    public boolean lock(
        @WebParam(partName = "session", name = "session", targetNamespace = "http://www.modelbus.org/Repository/")
        Session session,
        @WebParam(partName = "uri", name = "uri", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.String uri,
        @WebParam(partName = "timeout", name = "timeout", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.Object timeout
    ) throws InvalidValueException, NonExistingResourceException, RepositoryRuntimeException, LockedException, RepositoryAuthentificationException;

    @WebResult(name = "sessionID", targetNamespace = "http://www.modelbus.org/Repository/", partName = "sessionID")
    @WebMethod(action = "http://www.modelbus.org/Repository/authenticate")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.960+01:00")
    public java.lang.String authenticate(
        @WebParam(partName = "username", name = "username", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.String username,
        @WebParam(partName = "password", name = "password", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.String password
    ) throws InvalidValueException, RepositoryRuntimeException;

    @WebMethod(action = "http://www.modelbus.org/Repository/checkOutFile")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.960+01:00")
    public void checkOutFile(
        @WebParam(partName = "session", mode = WebParam.Mode.INOUT, name = "session", targetNamespace = "http://www.modelbus.org/Repository/")
        javax.xml.ws.Holder<Session> session,
        @WebParam(partName = "fileUri", name = "fileUri", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.String fileUri,
        @WebParam(partName = "revision", name = "revision", targetNamespace = "http://www.modelbus.org/Repository/")
        long revision,
        @WebParam(partName = "fileContent", mode = WebParam.Mode.OUT, name = "fileContent", targetNamespace = "http://www.modelbus.org/Repository/")
        javax.xml.ws.Holder<byte[]> fileContent
    ) throws RepositoryRuntimeException, NonExistingResourceException, RepositoryAuthentificationException;

    @WebMethod(action = "http://www.modelbus.org/Repository/checkOutModel")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.960+01:00")
    public void checkOutModel(
        @WebParam(partName = "session", mode = WebParam.Mode.INOUT, name = "session", targetNamespace = "http://www.modelbus.org/Repository/")
        javax.xml.ws.Holder<Session> session,
        @WebParam(partName = "modelUri", name = "modelUri", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.String modelUri,
        @WebParam(partName = "model", mode = WebParam.Mode.OUT, name = "model", targetNamespace = "http://www.modelbus.org/Repository/")
        javax.xml.ws.Holder<byte[]> model
    ) throws UnresolvedReferencesException, RepositoryRuntimeException, NonExistingResourceException, RepositoryAuthentificationException;

    @WebResult(name = "incomingReferencesInfos", targetNamespace = "http://www.modelbus.org/Repository/", partName = "incomingReferencesInfos")
    @WebMethod(action = "http://www.modelbus.org/Repository/getIncomingReferences")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.960+01:00")
    public IncomingReferencesInfoArray getIncomingReferences(
        @WebParam(partName = "session", name = "session", targetNamespace = "http://www.modelbus.org/Repository/")
        Session session,
        @WebParam(partName = "uri", name = "uri", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.String uri
    ) throws RepositoryRuntimeException, NonExistingResourceException, RepositoryAuthentificationException;

    @WebResult(name = "successful", targetNamespace = "http://www.modelbus.org/Repository/", partName = "successful")
    @WebMethod(action = "http://www.modelbus.org/Repository/uncontrol")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.960+01:00")
    public boolean uncontrol(
        @WebParam(partName = "session", name = "session", targetNamespace = "http://www.modelbus.org/Repository/")
        Session session,
        @WebParam(partName = "fragmentFileLocation", name = "fragmentFileLocation", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.String fragmentFileLocation,
        @WebParam(partName = "logMessage", name = "logMessage", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.String logMessage
    ) throws NonExistingResourceException, RepositoryRuntimeException, LockedException, RepositoryAuthentificationException;

    @WebMethod(action = "http://www.modelbus.org/Repository/createModelwithContent")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.960+01:00")
    public void createModelwithContent(
        @WebParam(partName = "session", mode = WebParam.Mode.INOUT, name = "session", targetNamespace = "http://www.modelbus.org/Repository/")
        javax.xml.ws.Holder<Session> session,
        @WebParam(partName = "initialModelContent", name = "initialModelContent", targetNamespace = "http://www.modelbus.org/Repository/")
        byte[] initialModelContent,
        @WebParam(partName = "modelUri", name = "modelUri", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.String modelUri,
        @WebParam(partName = "enableDependencies", name = "enableDependencies", targetNamespace = "http://www.modelbus.org/Repository/")
        boolean enableDependencies,
        @WebParam(partName = "logMessage", name = "logMessage", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.String logMessage,
        @WebParam(partName = "checksum", mode = WebParam.Mode.OUT, name = "checksum", targetNamespace = "http://www.modelbus.org/Repository/")
        javax.xml.ws.Holder<java.lang.String> checksum
    ) throws UnresolvedReferencesException, InvalidValueException, RepositoryRuntimeException, ConstraintViolationException, RepositoryAuthentificationException;

    @WebMethod(action = "http://www.modelbus.org/Repository/delete")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.960+01:00")
    public void delete(
        @WebParam(partName = "session", mode = WebParam.Mode.INOUT, name = "session", targetNamespace = "http://www.modelbus.org/Repository/")
        javax.xml.ws.Holder<Session> session,
        @WebParam(partName = "uri", name = "uri", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.String uri,
        @WebParam(partName = "logMessage", name = "logMessage", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.String logMessage,
        @WebParam(partName = "revision", name = "revision", targetNamespace = "http://www.modelbus.org/Repository/")
        long revision,
        @WebParam(partName = "result", mode = WebParam.Mode.OUT, name = "result", targetNamespace = "http://www.modelbus.org/Repository/")
        javax.xml.ws.Holder<java.lang.String> result
    ) throws NonExistingResourceException, RepositoryRuntimeException, LockedException, RepositoryAuthentificationException;

    @WebMethod(action = "http://www.modelbus.org/Repository/createModel")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.960+01:00")
    public void createModel(
        @WebParam(partName = "session", mode = WebParam.Mode.INOUT, name = "session", targetNamespace = "http://www.modelbus.org/Repository/")
        javax.xml.ws.Holder<Session> session,
        @WebParam(partName = "modelUri", name = "modelUri", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.String modelUri,
        @WebParam(partName = "metamodelUri", name = "metamodelUri", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.String metamodelUri,
        @WebParam(partName = "logMessage", name = "logMessage", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.String logMessage,
        @WebParam(partName = "model", mode = WebParam.Mode.OUT, name = "model", targetNamespace = "http://www.modelbus.org/Repository/")
        javax.xml.ws.Holder<byte[]> model
    ) throws UnresolvedReferencesException, InvalidValueException, RepositoryRuntimeException, ConstraintViolationException, RepositoryAuthentificationException;

    @WebMethod(action = "http://www.modelbus.org/Repository/createDir")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.960+01:00")
    public void createDir(
        @WebParam(partName = "session", mode = WebParam.Mode.INOUT, name = "session", targetNamespace = "http://www.modelbus.org/Repository/")
        javax.xml.ws.Holder<Session> session,
        @WebParam(partName = "dirUri", name = "dirUri", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.String dirUri,
        @WebParam(partName = "logMessage", name = "logMessage", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.String logMessage,
        @WebParam(partName = "checksum", mode = WebParam.Mode.OUT, name = "checksum", targetNamespace = "http://www.modelbus.org/Repository/")
        javax.xml.ws.Holder<java.lang.String> checksum
    ) throws RepositoryRuntimeException, RepositoryAuthentificationException;

    @WebResult(name = "successful", targetNamespace = "http://www.modelbus.org/Repository/", partName = "successful")
    @WebMethod(action = "http://www.modelbus.org/Repository/publishService")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.960+01:00")
    public boolean publishService(
        @WebParam(partName = "session", name = "session", targetNamespace = "http://www.modelbus.org/Repository/")
        Session session,
        @WebParam(partName = "properties", name = "properties", targetNamespace = "http://www.modelbus.org/Repository/")
        ServiceProperties properties
    ) throws RepositoryRuntimeException, InvalidServiceDescriptionException, RepositoryAuthentificationException;

    @WebMethod(action = "http://www.modelbus.org/Repository/commit")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.960+01:00")
    public void commit(
        @WebParam(partName = "session", mode = WebParam.Mode.INOUT, name = "session", targetNamespace = "http://www.modelbus.org/Repository/")
        javax.xml.ws.Holder<Session> session,
        @WebParam(partName = "createFileMap", name = "createFileMap", targetNamespace = "http://www.modelbus.org/Repository/")
        PathFileContentMapEntryArray createFileMap,
        @WebParam(partName = "checkInFileMap", name = "checkInFileMap", targetNamespace = "http://www.modelbus.org/Repository/")
        PathFileContentMapEntryArray checkInFileMap,
        @WebParam(partName = "folderPaths", name = "folderPaths", targetNamespace = "http://www.modelbus.org/Repository/")
        net.java.dev.jaxb.array.StringArray folderPaths,
        @WebParam(partName = "deletionPaths", name = "deletionPaths", targetNamespace = "http://www.modelbus.org/Repository/")
        net.java.dev.jaxb.array.StringArray deletionPaths,
        @WebParam(partName = "logMessage", name = "logMessage", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.String logMessage,
        @WebParam(partName = "checksum", mode = WebParam.Mode.OUT, name = "checksum", targetNamespace = "http://www.modelbus.org/Repository/")
        javax.xml.ws.Holder<java.lang.String> checksum
    ) throws InvalidValueException, RepositoryRuntimeException, LockedException, RepositoryAuthentificationException;

    @WebResult(name = "successful", targetNamespace = "http://www.modelbus.org/Repository/", partName = "successful")
    @WebMethod(action = "http://www.modelbus.org/Repository/unlock")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.960+01:00")
    public boolean unlock(
        @WebParam(partName = "session", name = "session", targetNamespace = "http://www.modelbus.org/Repository/")
        Session session,
        @WebParam(partName = "uri", name = "uri", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.String uri
    ) throws NonExistingResourceException, RepositoryRuntimeException, LockedException, RepositoryAuthentificationException;

    @WebMethod(action = "http://www.modelbus.org/Repository/getDir")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.960+01:00")
    public void getDir(
        @WebParam(partName = "session", mode = WebParam.Mode.INOUT, name = "session", targetNamespace = "http://www.modelbus.org/Repository/")
        javax.xml.ws.Holder<Session> session,
        @WebParam(partName = "uri", name = "uri", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.String uri,
        @WebParam(partName = "revision", name = "revision", targetNamespace = "http://www.modelbus.org/Repository/")
        long revision,
        @WebParam(partName = "includeCommitMessages", name = "includeCommitMessages", targetNamespace = "http://www.modelbus.org/Repository/")
        boolean includeCommitMessages,
        @WebParam(partName = "entries", mode = WebParam.Mode.OUT, name = "entries", targetNamespace = "http://www.modelbus.org/Repository/")
        javax.xml.ws.Holder<RepositoryDirEntryArray> entries,
        @WebParam(partName = "entry", mode = WebParam.Mode.OUT, name = "entry", targetNamespace = "http://www.modelbus.org/Repository/")
        javax.xml.ws.Holder<RepositoryDirEntry> entry
    ) throws InvalidRevisionException, RepositoryRuntimeException, NonExistingResourceException, RepositoryAuthentificationException;

    @WebMethod(action = "http://www.modelbus.org/Repository/createFile")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.960+01:00")
    public void createFile(
        @WebParam(partName = "session", mode = WebParam.Mode.INOUT, name = "session", targetNamespace = "http://www.modelbus.org/Repository/")
        javax.xml.ws.Holder<Session> session,
        @WebParam(partName = "fileUri", name = "fileUri", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.String fileUri,
        @WebParam(partName = "initialFileContent", name = "initialFileContent", targetNamespace = "http://www.modelbus.org/Repository/")
        byte[] initialFileContent,
        @WebParam(partName = "logMessage", name = "logMessage", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.String logMessage,
        @WebParam(partName = "checksum", mode = WebParam.Mode.OUT, name = "checksum", targetNamespace = "http://www.modelbus.org/Repository/")
        javax.xml.ws.Holder<java.lang.String> checksum
    ) throws InvalidValueException, RepositoryRuntimeException, RepositoryAuthentificationException;

    @WebMethod(action = "http://www.modelbus.org/Repository/checkPath")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.960+01:00")
    public void checkPath(
        @WebParam(partName = "session", mode = WebParam.Mode.INOUT, name = "session", targetNamespace = "http://www.modelbus.org/Repository/")
        javax.xml.ws.Holder<Session> session,
        @WebParam(partName = "uri", name = "uri", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.String uri,
        @WebParam(partName = "revision", name = "revision", targetNamespace = "http://www.modelbus.org/Repository/")
        long revision,
        @WebParam(partName = "nodeKind", mode = WebParam.Mode.OUT, name = "nodeKind", targetNamespace = "http://www.modelbus.org/Repository/")
        javax.xml.ws.Holder<RepositoryNodeKind> nodeKind
    ) throws RepositoryRuntimeException, NonExistingResourceException, RepositoryAuthentificationException;

    @WebMethod(action = "http://www.modelbus.org/Repository/getStatus")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.960+01:00")
    public void getStatus(
        @WebParam(partName = "session", name = "session", targetNamespace = "http://www.modelbus.org/Repository/")
        Session session,
        @WebParam(partName = "includeServices", name = "includeServices", targetNamespace = "http://www.modelbus.org/Repository/")
        boolean includeServices,
        @WebParam(partName = "serviceStatus", mode = WebParam.Mode.OUT, name = "serviceStatus", targetNamespace = "http://www.modelbus.org/Repository/")
        javax.xml.ws.Holder<ServiceStatusArray> serviceStatus,
        @WebParam(partName = "startupDate", mode = WebParam.Mode.OUT, name = "startupDate", targetNamespace = "http://www.modelbus.org/Repository/")
        javax.xml.ws.Holder<java.lang.Object> startupDate,
        @WebParam(partName = "location", mode = WebParam.Mode.OUT, name = "location", targetNamespace = "http://www.modelbus.org/Repository/")
        javax.xml.ws.Holder<java.lang.String> location,
        @WebParam(partName = "SecureLocation", mode = WebParam.Mode.OUT, name = "SecureLocation", targetNamespace = "http://www.modelbus.org/Repository/")
        javax.xml.ws.Holder<java.lang.String> secureLocation
    ) throws RepositoryRuntimeException, RepositoryAuthentificationException;

    @WebMethod(action = "http://www.modelbus.org/Repository/info")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.960+01:00")
    public void info(
        @WebParam(partName = "session", mode = WebParam.Mode.INOUT, name = "session", targetNamespace = "http://www.modelbus.org/Repository/")
        javax.xml.ws.Holder<Session> session,
        @WebParam(partName = "uri", name = "uri", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.String uri,
        @WebParam(partName = "revision", name = "revision", targetNamespace = "http://www.modelbus.org/Repository/")
        long revision,
        @WebParam(partName = "info", mode = WebParam.Mode.OUT, name = "info", targetNamespace = "http://www.modelbus.org/Repository/")
        javax.xml.ws.Holder<Info> info
    ) throws InvalidRevisionException, RepositoryRuntimeException, NonExistingResourceException, RepositoryAuthentificationException;

    @WebResult(name = "logEntries", targetNamespace = "http://www.modelbus.org/Repository/", partName = "logEntries")
    @WebMethod(action = "http://www.modelbus.org/Repository/getLogEntries")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.960+01:00")
    public RepositoryLogEntryArray getLogEntries(
        @WebParam(partName = "session", name = "session", targetNamespace = "http://www.modelbus.org/Repository/")
        Session session,
        @WebParam(partName = "targetPaths", name = "targetPaths", targetNamespace = "http://www.modelbus.org/Repository/")
        net.java.dev.jaxb.array.StringArray targetPaths,
        @WebParam(partName = "startRevision", name = "startRevision", targetNamespace = "http://www.modelbus.org/Repository/")
        long startRevision,
        @WebParam(partName = "endRevision", name = "endRevision", targetNamespace = "http://www.modelbus.org/Repository/")
        long endRevision,
        @WebParam(partName = "changedPath", name = "changedPath", targetNamespace = "http://www.modelbus.org/Repository/")
        boolean changedPath,
        @WebParam(partName = "strictNode", name = "strictNode", targetNamespace = "http://www.modelbus.org/Repository/")
        boolean strictNode,
        @WebParam(partName = "limit", name = "limit", targetNamespace = "http://www.modelbus.org/Repository/")
        long limit,
        @WebParam(partName = "includeMergedRevisions", name = "includeMergedRevisions", targetNamespace = "http://www.modelbus.org/Repository/")
        boolean includeMergedRevisions,
        @WebParam(partName = "revisionProperties", name = "revisionProperties", targetNamespace = "http://www.modelbus.org/Repository/")
        net.java.dev.jaxb.array.StringArray revisionProperties
    ) throws RepositoryRuntimeException, RepositoryAuthentificationException;

    @WebResult(name = "lockInfos", targetNamespace = "http://www.modelbus.org/Repository/", partName = "lockInfos")
    @WebMethod(action = "http://www.modelbus.org/Repository/getLocks")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.960+01:00")
    public LockInfoArray getLocks(
        @WebParam(partName = "session", name = "session", targetNamespace = "http://www.modelbus.org/Repository/")
        Session session,
        @WebParam(partName = "urlPrefix", name = "urlPrefix", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.String urlPrefix
    ) throws NonExistingResourceException, RepositoryRuntimeException, LockedException, RepositoryAuthentificationException;

    @WebMethod(action = "http://www.modelbus.org/Repository/exists")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.960+01:00")
    public void exists(
        @WebParam(partName = "session", mode = WebParam.Mode.INOUT, name = "session", targetNamespace = "http://www.modelbus.org/Repository/")
        javax.xml.ws.Holder<Session> session,
        @WebParam(partName = "uri", name = "uri", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.String uri,
        @WebParam(partName = "revision", name = "revision", targetNamespace = "http://www.modelbus.org/Repository/")
        long revision,
        @WebParam(partName = "exists", mode = WebParam.Mode.OUT, name = "exists", targetNamespace = "http://www.modelbus.org/Repository/")
        javax.xml.ws.Holder<Exists> exists
    ) throws RepositoryRuntimeException, NonExistingResourceException, RepositoryAuthentificationException;

    @WebResult(name = "successful", targetNamespace = "http://www.modelbus.org/Repository/", partName = "successful")
    @WebMethod(action = "http://www.modelbus.org/Repository/copy")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-11-17T21:23:47.960+01:00")
    public boolean copy(
        @WebParam(partName = "session", name = "session", targetNamespace = "http://www.modelbus.org/Repository/")
        Session session,
        @WebParam(partName = "srcPaths", name = "srcPaths", targetNamespace = "http://www.modelbus.org/Repository/")
        net.java.dev.jaxb.array.StringArray srcPaths,
        @WebParam(partName = "destPath", name = "destPath", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.String destPath,
        @WebParam(partName = "isMove", name = "isMove", targetNamespace = "http://www.modelbus.org/Repository/")
        boolean isMove,
        @WebParam(partName = "failWhenDstExists", name = "failWhenDstExists", targetNamespace = "http://www.modelbus.org/Repository/")
        boolean failWhenDstExists,
        @WebParam(partName = "logMessage", name = "logMessage", targetNamespace = "http://www.modelbus.org/Repository/")
        java.lang.String logMessage
    ) throws RepositoryRuntimeException, NonExistingResourceException, RepositoryAuthentificationException;
}
